tasks:
  - init:
      bundle install && 
      yarn &&
      bundle exec rake db:reset
  - command:
      bundle exec foreman start
ports:
  - port: 5000
  - port: 3000
  - port: 9514
  - port: 9515
  - port: 25222
